apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-service-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: greeter-service
      environment: staging
  template:
    metadata:
      labels:
        app: greeter-service
        environment: staging
    spec:
      containers:
        - image: javajolt/greeter-server@sha256:6ba1a07424bbc21761568b704034f3ad2cb0e57cc75fbd7122bc9a31178489d7
          imagePullPolicy: IfNotPresent
          name: greeter-server
          ports:
            - containerPort: 5000
